/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as STokenIndexRouteImport } from './routes/s.$token.index'
import { Route as STokenBoardIdRouteImport } from './routes/s.$token.$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenIndexRoute = STokenIndexRouteImport.update({
  id: '/s/$token/',
  path: '/s/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenBoardIdRoute = STokenBoardIdRouteImport.update({
  id: '/s/$token/$boardId',
  path: '/s/$token/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token/$boardId': typeof STokenBoardIdRoute
  '/s/$token/': typeof STokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token/$boardId': typeof STokenBoardIdRoute
  '/s/$token': typeof STokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token/$boardId': typeof STokenBoardIdRoute
  '/s/$token/': typeof STokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/board/$boardId'
    | '/invite/$token'
    | '/oauth/consent'
    | '/s/$token/$boardId'
    | '/s/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/board/$boardId'
    | '/invite/$token'
    | '/oauth/consent'
    | '/s/$token/$boardId'
    | '/s/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/board/$boardId'
    | '/invite/$token'
    | '/oauth/consent'
    | '/s/$token/$boardId'
    | '/s/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OauthConsentRoute: typeof OauthConsentRoute
  STokenBoardIdRoute: typeof STokenBoardIdRoute
  STokenIndexRoute: typeof STokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token/': {
      id: '/s/$token/'
      path: '/s/$token'
      fullPath: '/s/$token/'
      preLoaderRoute: typeof STokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token/$boardId': {
      id: '/s/$token/$boardId'
      path: '/s/$token/$boardId'
      fullPath: '/s/$token/$boardId'
      preLoaderRoute: typeof STokenBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  OauthConsentRoute: OauthConsentRoute,
  STokenBoardIdRoute: STokenBoardIdRoute,
  STokenIndexRoute: STokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
